In [1]:
#pip install pycountry

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import plotly.express as px
import pycountry
warnings.filterwarnings('ignore')

In [13]:
data = pd.read_parquet("data_raw/ess9.parquet.gzip")
data.head()

,name,essround,edition,proddate,idno,cntry,nwspol,netusoft,netustm,ppltrst,...,inwemm,inwtm,dweight,pspwght,pweight,anweight,domain,prob,stratum,psu
0,ESS9e03_1,9,3.1,17.02.2021,27,AT,60,Every day,180,2,...,7,46.0,0.581174,0.218111,0.302091,0.065890,2.0,0.001176,59,1688
1,ESS9e03_1,9,3.1,17.02.2021,137,AT,10,Every day,20,7,...,6,73.0,1.062772,0.413473,0.302091,0.124907,2.0,0.000643,79,88
2,ESS9e03_1,9,3.1,17.02.2021,194,AT,60,Most days,180,5,...,48,92.0,1.376509,2.270293,0.302091,0.685836,2.0,0.000496,11,938
3,ESS9e03_1,9,3.1,17.02.2021,208,AT,45,Every day,120,3,...,49,134.0,0.993399,0.386483,0.302091,0.116753,2.0,0.000688,74,1998
4,ESS9e03_1,9,3.1,17.02.2021,220,AT,30,Never,Not applicable,5,...,39,40.0,0.377353,1.032102,0.302091,0.311789,2.0,0.001811,99,601

In [14]:
columns = ['region', 'cntry', 'lrscale', 'ppltrst', 'pplfair', 'pplhlp', 'stfeco']
numericals = ['lrscale', 'ppltrst', 'pplfair', 'pplhlp', 'stfeco']
df = data[columns]

df['lrscale'] = df['lrscale'].replace({r"Don\'t know": np.nan,
                                                           "Don't know": np.nan,
                                                           'Refusal': np.nan,
                                                           'Left': 0,
                                                           'Right': 10,
                                                           'No answer': np.nan,
                                                           })

df['ppltrst'] = df['ppltrst'].replace({r"You can't be too careful": 0,
                                       "Most people can be trusted": 10,
                                       r"Don't know": np.nan,
                                       'No answer': np.nan,
                                       'Refusal': np.nan
                                       })

df['pplfair'] = df['pplfair'].replace({r"Most people try to take advantage of me": 0,
                                       "Most people try to be fair": 10,
                                       r"Don't know": np.nan,
                                       'No answer': np.nan,
                                       'Refusal': np.nan
                                       })

df['pplhlp'] = df['pplhlp'].replace({r"People mostly look out for themselves": 0,
                                     "People mostly try to be helpful": 10,
                                     r"Don't know": np.nan,
                                     'No answer': np.nan,
                                     'Refusal': np.nan
                                     })

df['stfeco'] = df['stfeco'].replace({r"Extremely dissatisfied": 0,
                                                     "Extremely satisfied": 10,
                                                     r"Don't know": np.nan,
                                                     'No answer': np.nan,
                                                     'Refusal': np.nan
                                                     })

for col in numericals:
    df[col] = df[col].astype(float)

df['trust'] = df[['ppltrst', 'pplfair', 'pplhlp']].mean(axis=1)
df.drop(['ppltrst', 'pplfair', 'pplhlp'], axis=1, inplace=True)
df = df.dropna()
print('done')

done

In [15]:
df.head()

  region cntry  lrscale  stfeco     trust
0   AT22    AT      9.0     8.0  2.000000
1   AT21    AT      5.0     8.0  7.333333
2   AT33    AT      5.0     5.0  6.333333
4   AT32    AT      5.0     7.0  5.666667
5   AT21    AT      3.0     9.0  7.000000